#!/usr/bin/env python3
"""Render a web-qa-format run report from `gh project item-list` JSON (stdin).

Usage:
  gh project item-list N --owner ORG --format json \
    | _report.py --run RUN-ID --env URL --suite NAME --date YYYY-MM-DD --out FILE
Writes the markdown report to --out and prints a one-line summary to stdout.
"""
import argparse, json, sys

ICON = {"Passed": "✅", "Failed": "❌", "Blocked": "⏸", "Skipped": "⏭", "Not run": "▢", "In progress": "▶"}


def field(item, *names):
    for n in names:
        if item.get(n) not in (None, ""):
            return item[n]
    return ""


def main():
    ap = argparse.ArgumentParser()
    for a in ("run", "env", "suite", "date", "out"):
        ap.add_argument(f"--{a}", default="")
    args = ap.parse_args()

    data = json.load(sys.stdin)
    items = data.get("items", data if isinstance(data, list) else [])
    # executions = board items for this run that have a Case (the run parent has none)
    ex = [i for i in items if field(i, "run") == args.run and field(i, "case")]

    counts = {k: 0 for k in ("Passed", "Failed", "Blocked", "Skipped", "Not run", "In progress")}
    sizes = {"S": 0, "M": 0, "L": 0}
    for i in ex:
        counts[field(i, "result") or "Not run"] = counts.get(field(i, "result") or "Not run", 0) + 1
        s = field(i, "size")
        if s in sizes:
            sizes[s] += 1
    total = len(ex)
    passed, failed, blocked, skipped = counts["Passed"], counts["Failed"], counts["Blocked"], counts["Skipped"]
    pct = lambda n: f"{(100*n/total):.1f}%" if total else "0.0%"
    pass_rate = pct(passed)  # canonical: passed / total

    L = []
    L.append("---")
    L += [f"run_id: {args.run}", f"suite: {args.suite}", f"environment: {args.env}", f"date: {args.date}"]
    L.append("---\n")
    L.append(f"# Test Run Report: {args.suite} — {args.date}\n")
    L.append(f"**Run:** {args.run} · **Environment:** {args.env}\n")
    L.append("## Summary\n")
    L.append("| Metric | Count | % |")
    L.append("|--------|-------|---|")
    L.append(f"| Total | {total} | 100% |")
    L.append(f"| ✅ Passed | {passed} | {pct(passed)} |")
    L.append(f"| ❌ Failed | {failed} | {pct(failed)} |")
    L.append(f"| ⏸ Blocked | {blocked} | {pct(blocked)} |")
    L.append(f"| ⏭ Skipped | {skipped} | {pct(skipped)} |")
    if any(sizes.values()):
        L.append("\n### Size Distribution\n")
        L.append("| Size | Count |")
        L.append("|------|-------|")
        for s in ("S", "M", "L"):
            L.append(f"| {s} | {sizes[s]} |")
    L.append("\n## Results\n")
    L.append("| Case | Title | Size | Result |")
    L.append("|------|-------|------|--------|")
    for i in sorted(ex, key=lambda x: field(x, "case")):
        r = field(i, "result") or "Not run"
        title = (i.get("content") or {}).get("title", "")
        title = title.split(" — ", 1)[-1]
        L.append(f"| {field(i,'case')} | {title} | {field(i,'size') or '—'} | {ICON.get(r,'')} {r} |")
    fails = [i for i in ex if field(i, "result") == "Failed"]
    if fails:
        L.append("\n## Failed Tests\n")
        for i in fails:
            url = (i.get("content") or {}).get("url", "")
            fr = field(i, "failureReason", "failure reason")
            L.append(f"### ❌ {field(i,'case')}")
            if fr:
                L.append(f"- Failure reason: `{fr}`")
            if url:
                L.append(f"- Issue: {url}")
    L.append("\n## Notes\n")
    L.append("> Generated by complete-run.sh from the QA Runs project board.\n")

    out = "\n".join(L)
    if args.out:
        open(args.out, "w", encoding="utf-8").write(out)
    print(f"Total {total} · Passed {passed} · Failed {failed} · Blocked {blocked} · Skipped {skipped} · Pass rate {pass_rate}")


if __name__ == "__main__":
    main()
