#!/usr/bin/env python3
"""Generate Obsidian vault hub notes from the test-case index.

Emits id-less notes (invisible to the case tooling):
  tests/_meta/requirements/<safe>.md   requirement proxy; links back to covering cases
  tests/<folder>/_index.md             suite/module MOC (recursive)
  tests/_index.md                      vault root MOC

Requirement refs stay bare in cases (e.g. OWNER/REPO#N); the proxy note carries a
derived GitHub URL and lists [[<case-id>]] of every covering case.
"""
import argparse, json, os, re, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _tc import read_frontmatter  # noqa: E402

GEN_MARK = "generated by onetest-tms build-index — do not edit"


def load_cases(index_path):
    return json.load(open(index_path, encoding="utf-8")).get("cases", [])


def safe_name(ref):
    return re.sub(r"[^A-Za-z0-9_.-]+", "-", ref).strip("-")


def derive_url(ref, default_repo):
    m = re.match(r"^([^/\s]+/[^#\s]+)#(\d+)$", ref)
    if m:
        return f"https://github.com/{m.group(1)}/issues/{m.group(2)}"
    if re.match(r"^#?\d+$", ref) and default_repo:
        return f"https://github.com/{default_repo}/issues/{ref.lstrip('#')}"
    return None


def collect_requirements(cases):
    covers = {}
    for c in cases:
        for ref in c.get("requirements", []):
            ref = ref.strip()
            if not ref:
                continue
            covers.setdefault(ref, [])
            if c["id"] not in covers[ref]:
                covers[ref].append(c["id"])
    return covers


def _req_note(ref, case_ids, url):
    lines = ["---", f'aliases: ["{ref}"]', "tags: [requirement]"]
    if url:
        lines.append(f"url: {url}")
    lines += ["---", "", f"# {ref}", ""]
    if url:
        lines += [f"External resource: <{url}>", ""]
    lines.append("## Covered by")
    lines += [f"- [[{cid}]]" for cid in sorted(case_ids)]
    lines += ["", f"<!-- {GEN_MARK} -->", ""]
    return "\n".join(lines)


def write_requirements(tests_dir, covers, default_repo=None):
    d = os.path.join(tests_dir, "_meta", "requirements")
    os.makedirs(d, exist_ok=True)
    written = []
    for ref in sorted(covers):
        p = os.path.join(d, f"{safe_name(ref)}.md")
        open(p, "w", encoding="utf-8").write(
            _req_note(ref, covers[ref], derive_url(ref, default_repo)))
        written.append(os.path.normpath(p))
    return written
