#!/usr/bin/env python3
"""Generate Obsidian vault hub notes from the test-case index.

Emits id-less notes (invisible to the case tooling):
  tests/_meta/requirements/<safe>.md   requirement proxy; links back to covering cases
  tests/<folder>/_index.md             suite/module MOC (recursive)
  tests/_index.md                      vault root MOC

Requirement refs stay bare in cases (e.g. OWNER/REPO#N); the proxy note carries a
derived GitHub URL and lists [[<case-id>]] of every covering case.
"""
import argparse, json, os, re, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

GEN_MARK = "generated by onetest-tms build-index — do not edit"


def load_cases(index_path):
    with open(index_path, encoding="utf-8") as f:
        return json.load(f).get("cases", [])


def safe_name(ref):
    return re.sub(r"[^A-Za-z0-9_.-]+", "-", ref).strip("-")


def derive_url(ref, default_repo):
    m = re.match(r"^([^/\s]+/[^#\s]+)#(\d+)$", ref)
    if m:
        return f"https://github.com/{m.group(1)}/issues/{m.group(2)}"
    if re.match(r"^#?\d+$", ref) and default_repo:
        return f"https://github.com/{default_repo}/issues/{ref.lstrip('#')}"
    return None


def collect_requirements(cases):
    covers = {}
    for c in cases:
        for ref in c.get("requirements", []):
            ref = ref.strip()
            if not ref:
                continue
            covers.setdefault(ref, [])
            if c["id"] not in covers[ref]:
                covers[ref].append(c["id"])
    return covers


def _req_note(ref, case_ids, url):
    lines = ["---", f'aliases: ["{ref}"]', "tags: [requirement]"]
    if url:
        lines.append(f"url: {url}")
    lines += ["---", "", f"# {ref}", ""]
    if url:
        lines += [f"External resource: <{url}>", ""]
    lines.append("## Covered by")
    lines += [f"- [[{cid}]]" for cid in sorted(case_ids)]
    lines += ["", f"<!-- {GEN_MARK} -->", ""]
    return "\n".join(lines)


def write_requirements(tests_dir, covers, default_repo=None):
    d = os.path.join(tests_dir, "_meta", "requirements")
    os.makedirs(d, exist_ok=True)
    written = []
    for ref in sorted(covers):
        p = os.path.join(d, f"{safe_name(ref)}.md")
        with open(p, "w", encoding="utf-8") as f:
            f.write(_req_note(ref, covers[ref], derive_url(ref, default_repo)))
        written.append(os.path.normpath(p))
    return written


def moc_tree(tests_dir, cases):
    folders = {"": {"cases": [], "subdirs": set()}}
    for c in cases:
        rel = os.path.relpath(c["path"], tests_dir)
        folder = os.path.dirname(rel)
        parts = folder.split(os.sep) if folder else []
        for i in range(len(parts) + 1):
            folders.setdefault(os.sep.join(parts[:i]), {"cases": [], "subdirs": set()})
        for i in range(len(parts)):
            folders[os.sep.join(parts[:i])]["subdirs"].add(os.sep.join(parts[:i + 1]))
        folders[folder]["cases"].append((c["id"], c.get("title", "")))
    return folders


def _moc_note(folder, data):
    title = folder.split(os.sep)[-1] if folder else "Test Vault"
    lines = ["---", "tags: [moc]", "---", "", f"# {title}", ""]
    if data["subdirs"]:
        lines.append("## Suites")
        for child in sorted(data["subdirs"]):
            lines.append(f"- [[{child}/_index|{child.split(os.sep)[-1]}]]")
        lines.append("")
    if data["cases"]:
        lines.append("## Cases")
        for cid, ttl in sorted(data["cases"]):
            lines.append(f"- [[{cid}]] — {ttl}")
        lines.append("")
    lines += [f"<!-- {GEN_MARK} -->", ""]
    return "\n".join(lines)


def write_mocs(tests_dir, cases):
    written = []
    for folder, data in moc_tree(tests_dir, cases).items():
        p = os.path.join(tests_dir, folder, "_index.md")
        os.makedirs(os.path.dirname(p), exist_ok=True)
        with open(p, "w", encoding="utf-8") as f:
            f.write(_moc_note(folder, data))
        written.append(os.path.normpath(p))
    return written
